#!/bin/bash

function green(){
    echo -e "\x1B[32m $1 \x1B[0m"
    if [ ! -z "${2}" ]; then
    echo -e "\x1B[32m $($2) \x1B[0m"
    fi
}

WORKING_DIR=$(dirname $0)/..

green "=== Updating python environment ==="

cd $WORKING_DIR && mamba env update -f environment.yml --prune
